packages:
  - 'Onoot-Boutique/*'
  - 'artifacts/*'
  - 'lib/*'
  - 'scripts'



catalog:
  vite: ^5.4.0
  '@types/node': ^20.14.2
  '@types/react': ^18.3.11
  '@types/react-dom': ^18.3.1
  '@vitejs/plugin-react': ^4.3.1
  '@tailwindcss/vite': ^4.0.0
  'drizzle-orm': ^0.36.4
  'tailwindcss': ^3.4.14
  'autoprefixer': ^10.4.20
  'class-variance-authority': ^0.7.1
  'clsx': ^2.1.1
  'tailwind-merge': ^2.5.2
  'framer-motion': ^11.11.1
  'lucide-react': ^0.445.0
  '@tanstack/react-query': ^5.56.2
  'react': ^18.3.1
  'react-dom': ^18.3.1
  'zod': ^3.23.8

allowBuilds:
  esbuild: true
