import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import cartRouter from "./cart";
import authRouter from "./auth";
import usersRouter from "./users";
import ordersRouter from "./orders";
import reviewsRouter from "./reviews";
import adminUsersRouter from "./adminUsers";
import adminAuthRouter from "./adminAuth";
import adminProductsRouter from "./adminProducts";
import adminRouter from "./admin";
import adminCategoriesRouter from "./adminCategories";
import adminReviewsRouter from "./adminReviews";
import adminNotificationsRouter from "./adminNotifications";
import adminDeliveryDriversRouter from "./adminDeliveryDrivers";
import promoVideosRouter from "./promoVideos";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(reviewsRouter);
router.use(usersRouter);
router.use(adminRouter);
router.use(promoVideosRouter);
router.use('/admin/products', adminProductsRouter);
router.use('/admin/categories', adminCategoriesRouter);
router.use('/admin/users', adminUsersRouter);
router.use('/admin/auth', adminAuthRouter);
router.use('/admin/reviews', adminReviewsRouter);
router.use('/admin/notifications', adminNotificationsRouter);
router.use('/admin/delivery-drivers', adminDeliveryDriversRouter);

export default router;
